### ISSUE TITLE
reselecting empty note fails to load

### ISSUE THREAD

**Issue by abahmed** [abahmed/Deer#135]
**Describe the bug**
When you have at least one note in the note list and you add a new note (empty one) and you select the other note then reelect the new one, it fails to be loaded. 

**To Reproduce**
1. Firstly, Add and save a new note
2. Add another new note and leave it empty
3. Select the other note
4. Re-select the empty note
5. See error

**Expected behavior**
The empty note should be loaded correctly to be edited

**Comment by jesusbibieca** [comment]
I'll be working on this.
