### ISSUE TITLE
prompt save note before selecting another note

### ISSUE THREAD

**Issue by abahmed** [abahmed/Deer#136]
**Describe the bug**
When you try to select another note after creating a new note and it's not save, but it's edited. it's not saved and your content is deleted.

**To Reproduce**
1. Firstly, Add and save a new note
2. Add another new note and add some text
3. Select the other note

**Expected behavior**
Prompt save note modal before selecting another note and get user response, process it then select the other note.

**Comment by nwyll** [comment]
I would like to work on this if that's ok. I am new to oss but have worked with React. I will fork the repo and start looking at the code.

**Comment by abahmed** [comment]
Hello Natalie,

Welcome to Deer and you are welcome to work on this issue. You can also read our documentation, join us on Gitter to ask, inquire about anything you need to know, or get helped.

**Comment by abahmed** [comment]
Hello Natalie (@nwyll) ,

Welcome to Deer and you are welcome to work on this issue. You can also read [Our Docs](.././tree/develop/docs/README.md), join us on [Gitter](https://gitter.im/abahmed/Deer) to ask, inquire about anything you need to know, or get helped.

**Comment by brickmaker17** [comment]
Are you still in need of help with this? If so I am willing to take a look at it and see what I can figure out?

**Comment by abahmed** [comment]
Hello Luke(@brickmaker17),

Firstly, welcome to Deer and we appreciate your desire for help, but it seems @nwyll still working on it. Deer always needs your help and contribution, so feel free to pick, report, suggest [an issue](https://github.com/abahmed/Deer/issues) and work on it or ping us on [Gitter](https://gitter.im/abahmed/Deer)

**Comment by jesusbibieca** [comment]
@nwyll Hey! Can you confirm that you are still working with this... Otherwise, someone else might be able to work on this or even give you some help if you are stuck. Just ping me and I can guide you if needed.

**Comment by jesusbibieca** [comment]
I'm taking this issue since no report of progress has been made.
