### ISSUE TITLE
Refactoring modals

### ISSUE THREAD

**Issue by abahmed** [abahmed/Deer#146]
**Is your feature request related to a problem? Please describe.**
Currently, we have two modals (Status and YesNo). We can refactor them, so they will be one component takes parameters (e.g. type, message, callback) instead of two components.

**Describe the solution you'd like**
Just create a component called "Modal" and replace it with two components through passing proper parameters to do the same functionality.

**Comment by enzo-beltrami** [comment]
I would like to work on this

**Comment by enzo-beltrami** [comment]
So, there is a lot of logic in the modals, should I move the logic to the parent component??

**Comment by abahmed** [comment]
@enzo-beltrami We can keep **one** component instead of all of them and it takes parameters
1. type
2. buttons (array)
3. message
4. callbacks
5. whatever..
any kind of parameters to keep one modal or dialog

**Comment by abahmed** [comment]
@enzo-beltrami Any updates?

**Comment by abahmed** [comment]
Modals is no longer used (PR #227)
