### ISSUE TITLE
Create About window

### ISSUE THREAD

**Issue by abahmed** [abahmed/Deer#15]
Create layout of the about window in resources/ui directory.

**All the following elements are centered.**
- It will be a small window and will have Deer's logo in the top.
- Then Deer with bold font
- Then the version number
- Then "A modern note-taking application allows you to write down your thoughts and ideas quickly and easily."
- Then with smaller font "Copyright © 2017 The Deer authors"

On the bottom right, there is Close button
On the bottom left, there is Credits button

Note: You can use RAD tool like Glade to generate the ui

**Comment by MahmoudYounes** [comment]
I will work on this
