### ISSUE TITLE
Add more devtools

### ISSUE THREAD

**Issue by enzo-beltrami** [abahmed/Deer#151]
**Describe the solution you'd like**
I would like to have things that speed our development cycle like hot-reload and debug tools eg. React and Redux browser extension.

**Comment by enzo-beltrami** [comment]
React Devtools
Redux Devtools
Hot-Reload (Don't know how to do it with Electron, maybe webpack-dev-server can do it?)

**Comment by jesusbibieca** [comment]
I was checking this and in order to have this tools at least the devtools you will need to have them installed first on your google chrome so electron can use them. 
Reference here: https://electronjs.org/docs/tutorial/devtools-extension

**Comment by jesusbibieca** [comment]
Hey just want to make you aware that this:
https://github.com/abahmed/Deer/pull/160/files#diff-e5b69ae680b6eecf6e38ec3504371c99R6
fixed the hot-reload... I was gonna add it and I saw it was there already! Now it's live reloading just fine. 

I'm checking how to add more dev tools as we talked before

**Comment by jesusbibieca** [comment]
I have not been able to add this... It will be available for anyone who want to give it a try
