### ISSUE TITLE
Keep showing welcome page till next is clicked

### ISSUE THREAD

**Issue by abahmed** [abahmed/Deer#154]
**Describe the bug**
Currently, we show welcome page once, even user didn't click on next button. this is not correct behavior as we need to keep showing welcome page till user clicks next button.

**To Reproduce**
1. Build and run Deer for first time
2. Close it
3. Open it again and it will not show welcome page

**Expected behavior**
 We need to keep showing welcome page till user clicks next button.

**Additional context**
Expected files that you will work on
https://github.com/abahmed/Deer/blob/develop/app/components/Home.js#L15
https://github.com/abahmed/Deer/blob/develop/app/components/Welcome.js#L36

**Comment by klauskpm** [comment]
I'd like to work on that.

**Comment by abahmed** [comment]
Hello Klaus (@klauskpm),

You are welcome to work on this issue. Don’t worry if you’re new, we are here to help you. You can read Our Docs, join us on [Gitter](https://gitter.im/abahmed/Deer) to ask, inquire about anything you need to know, or get helped.
