### ISSUE TITLE
Add tests for #145 and for #147

### ISSUE THREAD

**Issue by jesusbibieca** [abahmed/Deer#155]
**Describe the bug**
This two fixes are missing tests and would be really good if they were tested properly.

**Comment by mjimenez07** [comment]
I'll be taking a look into this @jesusbibieca @abahmed

**Comment by abahmed** [comment]
Hey @mjimenez07 go for it. You're welcome to contribute to Deer and you can join us on [Gitter](https://gitter.im/abahmed/Deer) for help or comments
