### ISSUE TITLE
YesNoModal is not being translated in different languages

### ISSUE THREAD

**Issue by jesusbibieca** [abahmed/Deer#164]
**Describe the bug**

If you change the language the yesNoModal is not being translated

![image](https://user-images.githubusercontent.com/29680762/46697703-3579f580-cbe3-11e8-87cc-cfb2a905b137.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by enzo-beltrami** [comment]
I'm working at #146 which should fix this when finished

**Comment by jesusbibieca** [comment]
@enzo-beltrami I'm so sorry I didn't see this and I opened a PR

**Comment by abahmed** [comment]
@jesusbibieca @enzo-beltrami 
It's not a problem, we can merge this now.
