### ISSUE TITLE
Let user select preferred language on welcome component

### ISSUE THREAD

**Issue by abahmed** [abahmed/Deer#167]
**Is your feature request related to a problem? Please describe.**
After landing issue #140 , Deer supports different languages, so it will be good to let user select  preferred language which is shown for the first time.

**Describe the solution you'd like**
You can use Settings component as a reference (https://github.com/abahmed/Deer/blob/develop/app/components/Settings.js). Maybe you need to factor out common code to avoid duplication as possible.

**Comment by Xhoria-RB** [comment]
Hello, i'm a beginner but i'll like to help with this issue to get experience.
