### ISSUE TITLE
YesNoModal is missing AR translation

### ISSUE THREAD

**Issue by jesusbibieca** [abahmed/Deer#169]
**Describe the bug**
After the `yesNoModal` was fixed the `yesBtn` and `noBtn` needs to be added and translated.

It should be done here: https://github.com/abahmed/Deer/blob/develop/assets/locales/ar/yesNoModal.json

Simply by adding the two properties mentioned before and adding it's respective translation should fix this.

**Comment by abahmed** [comment]
Fixed #169 with PR #179
