### ISSUE TITLE
Update link of Deer logo in README

### ISSUE THREAD

**Issue by abahmed** [abahmed/Deer#172]
**Describe the bug**
Currently, Deer uses relative path for its logo (in line 12) in README and this causes to be broken when it's used in [Electron Apps](https://electronjs.org/apps/deer).

**Comment by wptechprodigy** [comment]
I am working on this abahmed

**Comment by jesusbibieca** [comment]
Hello @wptechprodigy welcome to Deer and thank you for contributing. 

The link should take you to the full URL of the image

https://github.com/abahmed/Deer/blob/develop/assets/images/Deer-256.png

I hope you keep on contributing and you can join us on gitter. link in readme

**Comment by wptechprodigy** [comment]
Okay @jesusbibieca

**Comment by abahmed** [comment]
https://github.com/abahmed/Deer/blob/develop/assets/images/Deer-256.png

**Comment by wptechprodigy** [comment]
Kindly check on my PR
