### ISSUE TITLE
Add about us component

### ISSUE THREAD

**Issue by abahmed** [abahmed/Deer#176]
**Is your feature request related to a problem? Please describe.**
Add about us component contains Deer's contributors and Deer's logo too. You can just start a simple one, then it could be improved. @jesusbibieca @enzo-beltrami Any thought for the layout?

**Comment by mfecenko** [comment]
Hi, I would like to take this issue. Is it still unassigned?

**Comment by abahmed** [comment]
Hello, @mfecenko 

You are welcome to work on this issue. Don’t worry if you’re new, we are here to help you. You can read Our Docs, join us on [Gitter](https://gitter.im/abahmed/Deer) to ask, inquire about anything you need to know, or get helped.

**Comment by Rudy-Menekam** [comment]
hello,

**Comment by abahmed** [comment]
@Rudy-Menekam Hello :-)

**Comment by mfecenko** [comment]
I have a lot of work so I didn't have time to do it. @Rudy-Menekam if you want, you can take this issue.

**Comment by festMikolaj** [comment]
Hi :)
@Rudy-Menekam are you still working on this?

**Comment by abahmed** [comment]
This issue can be done using https://github.com/rhysd/electron-about-window

**Comment by festMikolaj** [comment]
@abahmed, since there is no response from @Rudy-Menekam, can I work on this issue?

**Comment by abahmed** [comment]
@

**Comment by abahmed** [comment]
@festMikolaj Yes, go on!

**Comment by abahmed** [comment]
Hey @festMikolaj , any updates?

**Comment by festMikolaj** [comment]
Hi @abahmed! I installed the package and tried to use it in Deer. Right now it doesn't work properly and I have some error messages. Should I make PR so you could look at it too?

**Comment by jesusbibieca** [comment]
@festMikolaj Yes, that way not only him, but all can check and even offer help on it. Just mark it as a Work in progress

**Comment by festMikolaj** [comment]
here you go #213
