### ISSUE TITLE
Set height and width of main window

### ISSUE THREAD

**Issue by abahmed** [abahmed/Deer#18]
Set height and width of main window to start with **fixed** height and width.
Width should be twice or more the height
e.g height: 360, width: 720 or more (select width that makes sense and has better view).

**Comment by ns23** [comment]
Hello, I would like to take this issue

**Comment by abahmed** [comment]
Hello Nitesh,

Deer's community welcomes you and we wish to continue contributing to it. it's OK to work on this issue. Firstly, you need have a look on our wiki (https://github.com/abahmed/Deer/wiki)
If there is something not clear, feel free to ping us.

I'd recommend you to add yourself to AUTHORS file. Also, you can recommend this project for your friends who will be interested.

**Comment by ns23** [comment]
Okay..I will read the wiki and start working on the issue.
It will take some time to go through the code as I am new to c++.

**Comment by ns23** [comment]
@abahmed 
Can  I use 
`gtk_widget_set_size_request(GTK_WIDGET(window), 720, 360);
    gtk_window_set_resizable(GTK_WINDOW(window), false);`
To set fixed  window width and height ?

**Comment by abahmed** [comment]
Thanks @ns23 for your interest. Deer's implementation has been switched to Electron and Node JS.
Currently, this task is easier. All you need is to make your changes here (https://github.com/abahmed/Deer/blob/master/main-process/main.js#L11)

**Comment by ns23** [comment]
Okay sure, I will start working on it tonight

**Comment by abahmed** [comment]
@ns23 You could work on this issue now?

**Comment by ns23** [comment]
@abahmed I will start working on it.And I will create the PR by tomorrow
