### ISSUE TITLE
Combine screenshots in README into a gif

### ISSUE THREAD

**Issue by abahmed** [abahmed/Deer#181]
**Is your feature request related to a problem? Please describe.**
Combine screenshots in README into a GIF
It would be better to use updated screenshots for develop branch.

**Comment by abahmed** [comment]
Hello @Rudy-Menekam ,

Welcome to Deer. Unfortunately, @andrasbacsai is working on it right now. You can pick another issue from our [issues](https://github.com/abahmed/Deer/issues). Don’t worry if you’re new, we are here to help you. You can read Our Docs, join us on [Gitter](https://gitter.im/abahmed/Deer) to ask, inquire about anything you need to know, or get helped.

**Comment by Rudy-Menekam** [comment]
ok thanks
