### ISSUE TITLE
Fix ru message translation

### ISSUE THREAD

**Issue by artywhite** [abahmed/Deer#189]
Fix Russian message translation `homeContent:thereIsNoNotesYetCreate` (added in https://github.com/abahmed/Deer/issues/188)

**Comment by artywhite** [comment]
@abahmed, sorry for no creating issues for first 2 PRs.
And thanks for merging them :)

**Comment by abahmed** [comment]
@artywhite you are welcome :-)

**Comment by abahmed** [comment]
@artywhite you are welcome :-)
