### ISSUE TITLE
Editor is empty after loading settings

### ISSUE THREAD

**Issue by abahmed** [abahmed/Deer#192]
**Describe the bug**
When you open or create a note and click on settings, then getting back. The editor will be empty.

**To Reproduce**
1. Open a note or create one and put text in it
2. Click on Settings
3. Click on Save or Cancel

**Expected behavior**
We could solve that by saving editor state as it seems it's not saved

**Comment by mateuszhoffman** [comment]
Let's get started!

**Comment by abahmed** [comment]
Fixed with PR #218
