### ISSUE TITLE
Add a Static Toolbar to NoteEditor

### ISSUE THREAD

**Issue by abahmed** [abahmed/Deer#200]
**Is your feature request related to a problem? Please describe.**
Add a Static Toolbar to NoteEditor to allow us build a Rich Text Editor suitable for Deer users

**Comment by medha-yadav** [comment]
Hi I would like to work on this issue.

**Comment by abahmed** [comment]
Hey @medha-yadav 

You are welcome to work on this issue, but just confirm with us what you going to do to avoid un-useful work. Don’t worry if you’re new, we are here to help you. You can read Our Docs, join us on [Gitter](https://gitter.im/abahmed/Deer) to ask, inquire about anything you need to know, or get helped.

**Comment by theperfectpunk** [comment]
Hey @medha-yadav, just wanted to know if you're still working on this... I have just started working on this, so please let me know to avoid doing what you might have already done again :)
