### ISSUE TITLE
high level task runners

### ISSUE THREAD

**Issue by MahmoudYounes** [abahmed/Deer#216]
**Is your feature request related to a problem? Please describe.**
I am always frustrated that I have to type in two commands through the console to get Deer to work. the build command and the start command.

**Describe the solution you'd like**
integrate high level task runners like gulp in the development work flow. Or add one dev command to the packages.json

**Describe alternatives you've considered**
as an alternative one may still use the existing method, or use grunt. lot's of plugins exist to help with electron distribution. gulp is more preferable than npm scripts and grunt because it's a streaming utility, is high level, and works well with node.

**Additional context**
nope.

**Update**
The issue mentioned that no automatic refresh on save but there actually is. My mistake!

**Comment by abahmed** [comment]
Fixed by PR #227
