### ISSUE TITLE
Notebooks to group notes

### ISSUE THREAD

**Issue by MahmoudYounes** [abahmed/Deer#217]
**Is your feature request related to a problem? Please describe.**
notes not organized by a notebook 

**Describe the solution you'd like**
allow user to create notebooks then assign notes to notebook

**Describe alternatives you've considered**
placing tags

**Comment by MahmoudYounes** [comment]
I am going to work on this

**Comment by Lionel-Stewart** [comment]
I am going to work on this

**Comment by Lionel-Stewart** [comment]
Just checking, but shouldn't this issue be closed?

**Comment by abahmed** [comment]
@Lionel-Stewart Yes. Feel free to join us on [Gitter channel](https://gitter.im/abahmed/Deer). Also if you have any suggestions feel free to create issues too
