### ISSUE TITLE
Switching Deer's implementation to Electron and Node JS

### ISSUE THREAD

**Issue by abahmed** [abahmed/Deer#22]
As Per Issue #19, we have started switching Deer's implementation to Electron and Node JS.
Currently, there is an **experimental** branch on which the new implementation lies. It just contains hello world window (which adapted from Electron's template).

Before starting creating issues / implementation, it's good to share your ideas, thoughts or suggestions .

@ai-zahran

**Comment by Venkat5694** [comment]
Here are a few things I believe we might start with:
[React](https://github.com/facebook/react)
[Redux](https://github.com/reactjs/redux)
[Webpack](https://github.com/webpack/webpack)
And a datastore:
Maybe [PouchDB](https://github.com/pouchdb/pouchdb)
or [localForage](https://github.com/localForage/localForage)

**Comment by abahmed** [comment]
@Venkat5694 I'm not sure what you meant exactly with React, Redux and Webpack. Currently, we need to focus on desktop application. It would be great to port Deer to mobile platforms and support different environments (client and server).

I prefer to go with PouchDB as a NoSQL Databases and for being used as a direct interface to CouchDB-compatible servers. Maybe you different thoughts?

**Comment by Venkat5694** [comment]
@abahmed  React is a front-end framework for web applications, which is used in most web-UI's today. It is component based and has wonderful support across various browsers.
Redux is a state engine (like Flux) which helps you have consistent state management and helps you write applications that behave consistently.
And Webpack is a bundler, which helps transpile ES5/6 javascript code into browser compatible code.

Electron is just a node + V8 runtime engine which wraps your app and serves it across platforms.
It also provides APIs to access OS specific functions(like tray icons, notifications, etc,.).

**Comment by Venkat5694** [comment]
Electron serves web-pages (either static or hosted). In our case the sample app currently serves the index.html file. We will write the components that are needed in react and webpack will compile it into js files which will be included in the index.html

[Manta](https://github.com/hql287/Manta) is an offline desktop app which is built on electron.
It would give you a good idea about how a desktop app using electron can be built.

**Comment by abahmed** [comment]
Aha, you are right!
I think this template (https://github.com/pastahito/electron-react-webpack) might help.
