### ISSUE TITLE
note loaded and note deleted message are not informative

### ISSUE THREAD

**Issue by MahmoudYounes** [abahmed/Deer#220]
**Describe the bug**
the note loaded message that appears after loading a note does not add any information to the user and it takes about a second to appear and disappear which is annoying. IMHO, users want to load a note and then start working directly. same goes for the note deleted message.

**To Reproduce**
1. select a previously saved note
2. message will appear with content "note loaded"

**Expected behavior**
editor's content changing without the messages appearing

**Comment by abahmed** [comment]
Fixed by PR #227
