### ISSUE TITLE
Open a default note on startup

### ISSUE THREAD

**Issue by shieldgenerator7** [abahmed/Deer#247]
<h3>Description</h3>
Currently when you first open the app, it greets you with the home screen and the list of notes on the side. Ideally, it would instead just open up the default note, which could be the most recently opened note. I would like it to open up to one of the already existing notes instead of the home screen.

<h3>Alternatives:</h3>

On Start up:
- Open up the most recently edited note
- Open up the most recently selected note
- Open up a new note
-or-
- Provide options in the settings as to what to do on startup (like Chrome does)

**Comment by ganesh-4212** [comment]
I'm interested to work on this issue.

**Comment by abahmed** [comment]
Great! Go on, and if you have a problem ping me on Gitter 👍

**Comment by sensokame** [comment]
@ganesh-4212 hello, are you still working on this issue, I can take over if you have other things to do.

**Comment by Lionel-Stewart** [comment]
I'm interested to work on this issue. Since the last person commented over a month ago, I'll start working on it.

**Comment by Lionel-Stewart** [comment]
I'm interested in working on this issue. @sensokame are you still working on this issue? I'm willing to try if you are not working on it or don't mind.

**Comment by sensokame** [comment]
I actually didn't get a response about the state of this issue, so you're free to do what you think is right :p

**Comment by sensokame** [comment]
@Lionel-Stewart the pull request I made could even give you an idea (it's already working, but needs review)

**Comment by abahmed** [comment]
@sensokame I've not seen your work, make a Pull Request to get reviewed and merged

**Comment by Lionel-Stewart** [comment]
Well so much for working on this issue... Oh well, it was a good experience at least

**Comment by abahmed** [comment]
> Well so much for working on this issue... Oh well, it was a good experience at least

Hey Lionel, there is another opened issue #217 , If you would like to work on @Lionel-Stewart ?

**Comment by Lionel-Stewart** [comment]
Thanks for the suggestion, I studied the project's code trying to solve this solution, so it'll be easier to solve issue 217. I'll start working on that right now.
