### ISSUE TITLE
deleting note crashes the app

### ISSUE THREAD

**Issue by mahendraHegde** [abahmed/Deer#268]
**Describe the bug**
deleting note  which belongs to noteBook and trying to add a new note to the same notebook crashing the app 
**To Reproduce**
1.  create a notebook `test`.
2.  selects the new notebook `test` (applybtn)
3. add a new note to notebook `test`
4. delete the note(without removing it from the notebook `test`)
5. select the the notebook `test` and  click `OPENBTN`.// **important**
6. click on add new Note icon
App will crash

**Expected behavior**
App should not crash on deleting note belonging to a notebook.

@abahmed I have fixed this bug. I'd like to raise a pull request.

**Comment by abahmed** [comment]
@mahendraHegde Yes, sure please
