### ISSUE TITLE
Add webpack-dev-server for hot reloading modules in dev

### ISSUE THREAD

**Issue by Venkat5694** [abahmed/Deer#28]
Add webpack-dev-server dependency and the corresponding build script.
Update `Building and Installing` wiki to reflect new dev vs. prod scripts.

Add [electron-reloader](https://github.com/sindresorhus/electron-reloader) for reloading electron main process.

**Comment by mohamed-moanis** [comment]
webpack configuration has the `watch` option. How that differs from `webpack-dev-server`.

**Comment by Venkat5694** [comment]
`watch` option in webpack re-compiles every time a file changes in the specified path. But this change will not reflect in the webpage which is being served by electron. `webpack-dev-server` on the other hand re-compiles and also reloads the UI on changes which saves a ton of time during development.

**Comment by mohamed-moanis** [comment]
@Venkat5694 But electron-reloader will reload the UI when webpack compiles new changes as in [this example](https://github.com/pastahito/electron-react-webpack/blob/master/main.js). Am I missing something?

**Comment by Venkat5694** [comment]
I missed the `electron-reload` part in `electron-react-webpack` bootstrap.
That should do the trick.

**Comment by mohamed-moanis** [comment]
Cool, you may edit the heading.
