### ISSUE TITLE
Create an empty window using GTK3

### ISSUE THREAD

**Issue by abahmed** [abahmed/Deer#5]
Create an empty window using GTK3 and GtkBuilder

You can use this example (https://developer.gnome.org/gtk3/3.0/gtk-getting-started.html) in Building interfaces, just the window without buttons and hello world.

Note:
- This is not a copy-paste issue. You need to think how to apply this example in the current structure of Deer.
- Each time you make a progress, just pull request the code you have done to get review, instead of pushing all your work that took much time and getting negative review.

**Comment by AbdelrahmanWaheed** [comment]
I will work on it
