### ISSUE TITLE
Evaluate various UI frameworks

### ISSUE THREAD

**Issue by Venkat5694** [abahmed/Deer#70]
Deer should reuse UI components provided by various UI frameworks. Evaluate frameworks to zero in on any one framework that would predominantly be used in Deer.

**Comment by abahmed** [comment]
What about using Ant-design (https://ant.design)? @Venkat5694

**Comment by Venkat5694** [comment]
Ant-design definitely seems to be the most mature/extensive design framework among the ones we considered. I agree with @abahmed on this. Let's get the wheel rolling on our bare-bone UI.
