### ISSUE TITLE
Show Welcome component for the first time

### ISSUE THREAD

**Issue by abahmed** [abahmed/Deer#86]
**Is your feature request related to a problem? Please describe.**
Currently, Welcome component is shown every time user runs Deer.

**Describe the solution you'd like**
We should show Welcome component only for the first time. 

**Additional context**
You can use electron-store package to accomplish that through set a user preference (e.g. show-welcome) with false value, so each time user runs Deer check for this pref and do necessary routing or redirecting. (Ask here for any missing information, something is not clear, or needing some help)

**Comment by MahmoudYounes** [comment]
I will work on this
